authors:
  HYP3R00T:
    name: Rajesh Kumar Das
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/78068806?v=4
    url: https://github.com/HYP3R00T

  jazo:
    name: James Lazo
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/131928783?v=4
    url: https://github.com/jameslazo