apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mischavandenburg/kubecraft.git
    targetRevision: HEAD
    path: "./argocd/apps-children/"
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

